### ISSUE TITLE
So, when will you finish this mod?

### ISSUE THREAD

**Issue by aggelosQQ** [tylerhyperHD/FreedomHostingMod#3]
Please, do not be Inactive on immafreedommod's development.

**Comment by LegendIsAwesomes** [comment]
This project will take some time @aggelosqq maybe January next year, it will take a lot of work so just use the TFM ifm

**Comment by aggelosQQ** [comment]
Fine, however, do not leave the development of the other mod.

**Comment by LegendIsAwesomes** [comment]
We wont

**Comment by AlphaGaming** [comment]
Hello

**Comment by tylerhyperHD** [comment]
Developing a mod takes time and effort and since I have had no time but a ton of effort you need to bear with the fact that development will be slow no matter what in this situation.

**Comment by LegendIsAwesomes** [comment]
@tylerhyperHD I plan to work a ton on this mod, when I know what to add.
